image: node:16.20.0-slim

before_script:
  - echo ':before_script'
  - cat /etc/os-release
  - npm --version
  - node --version
  - npm install
  - echo 'end :before_script'

cache:
  untracked: true
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

deploy:
  image: python:3.8-slim
  stage: deploy
  when: manual
  before_script:
    - echo ':before_script'
  only:
    - master
  script:
    - pip install awscli==1.17.13
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 rm s3://test-aws-yt-tut2 --recursive
    - aws s3 sync ./dist s3://test-aws-yt-tut2 --acl public-read
