image: node:16.20.0-slim

before_script:
  - echo ':before_script'
  - cat /etc/os-release
  - npm --version
  - node --version
  - npm install
  - echo 'end :before_script'

cache:
  untracked: true
  paths:
    - node_modules/

variables:
  UNIT_TESTS_PUBLIC_FOLDER: "public/unit-tests"
  PROJECT_NAME: "continuous-deployment-spa-on-aws"
  UNIT_TEST_ANGULAR_FOLDER: "coverage/$PROJECT_NAME"
  BUCKET_NAME: "aws-spa-tutorial"

stages:
  - test
  - build
  - deploy

test:
  image: timbru31/node-chrome:16-alpine
  script:
    - npm run test:ci
  coverage: '/Statements\s+:\s(\d+.\d+)%/'
  artifacts:
    paths:
      - $UNIT_TEST_ANGULAR_FOLDER
    expire_in: 1 hour
    reports:
      junit:
        - Chrome_Headless_114.0.5735.106_(Linux_x86_64)/junit.xml

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

pages:
  stage: deploy
  script:
    - echo 'Cleaning old pages'
    - rm -rf public
    - ls -la
    - mkdir -p $UNIT_TESTS_PUBLIC_FOLDER && cp -r $UNIT_TEST_ANGULAR_FOLDER/* $UNIT_TESTS_PUBLIC_FOLDER
    - echo 'Public directory content after copying files'
    - ls -la ./public
  artifacts:
    paths:
      - public
    expire_in: 1 hour
  only:
    - master

aws_cli_v1:
  image: python:3.8-slim
  stage: deploy
  when: manual
  before_script:
    - echo ':before_script'
    - python --version
    - pip --version
  script:
    - pip install awscli==1.27.148
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 rm s3://$BUCKET_NAME --recursive
    - aws s3 sync ./dist/$PROJECT_NAME s3://$BUCKET_NAME --acl public-read

# Following variables have to be set:
# - AWS_ACCESS_KEY_ID
# - AWS_SECRET_ACCESS_KEY
# - AWS_DEFAULT_REGION
# Ref: https://docs.gitlab.com/ee/ci/cloud_deployment/#use-an-image-to-run-aws-commands
aws_gitlab:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  when: manual
  before_script:
    - echo ':before_script'
    - cat /etc/os-release
  script:
    - aws s3 rm s3://$BUCKET_NAME --recursive
    - aws s3 sync ./dist/$PROJECT_NAME s3://$BUCKET_NAME --acl public-read
