image: node:16.20.0-slim

before_script:
  - echo ':before_script'
  - cat /etc/os-release
  - npm --version
  - node --version
  - npm install
  - echo 'end :before_script'

cache:
  untracked: true
  paths:
    - node_modules/

variables:
  UNIT_TESTS_PUBLIC_FOLDER: "public/unit-tests"
  UNIT_TEST_ANGULAR_FOLDER: "coverage/continuous-deployment-spa-on-aws"

stages:
  - test
  - build
  - deploy

test:
  image: timbru31/node-chrome:16-alpine
  script:
    - npm run test:ci
  coverage: '/Statements\s+:\s(\d+.\d+)%/'
  artifacts:
    paths:
      - $UNIT_TEST_ANGULAR_FOLDER
    expire_in: 1 hour
    reports:
      junit:
        - Chrome_Headless_114.0.5735.106_(Linux_x86_64)/junit.xml

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

pages:
  stage: deploy
  script:
    - echo 'Cleaning old pages'
    - rm -rf public
    - ls -la
    - mkdir -p $UNIT_TESTS_PUBLIC_FOLDER && cp -r $UNIT_TEST_ANGULAR_FOLDER/* $UNIT_TESTS_PUBLIC_FOLDER
    - echo 'Public directory content after copying files'
    - ls -la ./public
  artifacts:
    paths:
      - public
    expire_in: 1 hour
  only:
    - master

aws:
  image: python:3.8-slim
  stage: deploy
  when: manual
  before_script:
    - echo ':before_script'
  only:
    - master
  script:
    - pip install awscli==1.17.13
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 rm s3://test-aws-yt-tut2 --recursive
    - aws s3 sync ./dist s3://test-aws-yt-tut2 --acl public-read
