stages:
  - build
  - deploy

build:
  image: node:10.16.0-slim
  stage: build
  script:
    - npm install -g @angular/cli@7.3.9
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

deploy:
  image: python:latest
  stage: deploy
  only:
    - master
  script:
    - pip install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 rm s3://test-aws-yt-tut2 --recursive
    - aws s3 sync ./dist s3://test-aws-yt-tut2 --acl public-read

